import React from 'react'

export const Btn=({children,onClick,v='primary',disabled,full,sm,style={},c,accent})=>{const bg={primary:{background:accent||c?.A||'#CDFF6C',color:'#0A0A0A'},secondary:{background:c?.CARD||'#141414',color:c?.T||'#F0EBE1',border:`1px solid ${c?.BD||'#2A2A2A'}`},wa:{background:'#25D366',color:'#fff'},danger:{background:'#ff4444',color:'#fff'}};return<button onClick={onClick} disabled={disabled} style={{padding:sm?'8px 14px':'13px 20px',borderRadius:'12px',border:'none',cursor:disabled?'not-allowed':'pointer',fontSize:sm?'13px':'15px',fontWeight:'600',fontFamily:'inherit',opacity:disabled?.3:1,width:full?'100%':'auto',transition:'opacity .15s',...(bg[v]||bg.secondary),...style}}>{children}</button>;};
export const Inp=({value,onChange,onKey,placeholder,type='text',mono,c})=><input value={value} onChange={e=>onChange(e.target.value)} onKeyDown={onKey} placeholder={placeholder} type={type} style={{background:c?.CARD,border:`1px solid ${c?.BD}`,borderRadius:'10px',padding:'12px 14px',color:c?.T,fontSize:mono?'22px':'14px',fontFamily:mono?'monospace':'inherit',outline:'none',width:'100%',letterSpacing:mono?'.18em':'normal',fontWeight:mono?'800':'400',boxSizing:'border-box'}}/>;
export const Txa=({value,onChange,placeholder,rows=3,c})=><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={rows} style={{background:c?.CARD,border:`1px solid ${c?.BD}`,borderRadius:'10px',padding:'12px 14px',color:c?.T,fontSize:'14px',fontFamily:'inherit',outline:'none',width:'100%',resize:'vertical',boxSizing:'border-box',lineHeight:1.6}}/>;
export const Lbl=({children,c})=><div style={{fontSize:'11px',color:c?.M||'#555',fontWeight:'600',letterSpacing:'.07em',textTransform:'uppercase',marginBottom:'8px'}}>{children}</div>;
export const HR=({c})=><div style={{height:'1px',background:c?.BD,margin:'20px 0'}}/>;
export const Back=({onClick,label,c})=><button onClick={onClick} style={{background:'none',border:'none',color:c?.M2,cursor:'pointer',fontSize:'14px',padding:'0 0 22px',fontFamily:'inherit',display:'block'}}>{label}</button>;
export const Badge=({children,color})=><span style={{fontSize:'11px',fontWeight:'700',padding:'3px 10px',borderRadius:'20px',background:`${color}18`,color,border:`1px solid ${color}35`}}>{children}</span>;
export const Card=({children,style={},c,accent})=><div style={{background:c?.CARD,border:`1px solid ${accent?c?.A+'50':c?.BD}`,borderRadius:'14px',padding:'16px',marginBottom:'10px',...style}}>{children}</div>;
export const Stepper=({cur,labels,c,accent})=><div style={{display:'flex',gap:'6px',marginBottom:'28px'}}>{labels.map((s,i)=><div key={s} style={{flex:1,textAlign:'center'}}><div style={{height:'3px',borderRadius:'2px',background:i<=cur?accent||c?.A:c?.BD,marginBottom:'6px',transition:'background .3s'}}/><span style={{fontSize:'11px',color:i===cur?accent||c?.A:c?.M,fontWeight:i===cur?'700':'400'}}>{s}</span></div>)}</div>;
